### Create a new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "asfd@asdf.com",
    "password": "bajdbhjdbajd"
}

### Get user by id

GET http://localhost:3000/auth/1

### Get all users of same email
GET http://localhost:3000/auth?email=asfd@asdf.com

### Delete a user with given id
DELETE http://localhost:3000/auth/2

### Update user with id

PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "email": "riya@gmail.com"
}